# Generated by Django 4.2.11 on 2024-04-18 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=100, null=True)),
                ('cus_add', models.TextField(null=True)),
                ('cus_email', models.EmailField(blank=True, max_length=254)),
                ('cus_mob', models.CharField(max_length=15, null=True)),
                ('cus_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('cus_gstno', models.CharField(max_length=15, null=True)),
                ('cus_due', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('CE', 'Cement'), ('HA', 'Hardware'), ('PA', 'Paint'), ('SB', 'Steel Bars'), ('SI', 'Steel Items'), ('PV', 'PVC'), ('EL', 'Electrical')], max_length=2, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('NU', 'NUMBER'), ('KG', 'KILOGRAMS'), ('LT', 'LITRE'), ('MT', 'METER'), ('PC', 'PIECE')], max_length=20, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('hsn', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('product_date', models.DateField(default=datetime.date.today)),
                ('exp_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=100, null=True)),
                ('sup_add', models.TextField(null=True)),
                ('sup_category', models.CharField(max_length=100, null=True)),
                ('sup_gstno', models.CharField(blank=True, max_length=20, null=True)),
                ('sup_email', models.EmailField(max_length=254, null=True)),
                ('sup_cpn', models.CharField(blank=True, max_length=100, null=True)),
                ('sup_mob', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='movies.sale')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movies.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.product')),
            ],
        ),
    ]
