# Generated by Django 4.2.10 on 2024-02-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_customer_login_product_supplier_salesinvoice_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cus_gstno',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
