# Generated by Django 4.2.11 on 2024-04-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_product_brand_product_category_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_add',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_mob',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
