# Generated by Django 4.2.11 on 2024-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_customer_cus_add_alter_customer_cus_mob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='MovieInfo',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_add',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_mob',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
