# Generated by Django 4.2.11 on 2024-04-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_delete_director_delete_movieinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_due',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cus_gstno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
